---
  - name: Create ingester user
    user:
      name: ingester
      shell: /bin/bash
      groups: 
        - spamchamp
      append: yes

  - name: Install Service
    template: 
      src: templates/service.j2 
      dest: /etc/systemd/system/ingester.service